name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup permissions
        run: chmod +x ./run_tests.sh

      - name: Run tests
        run: ./run_tests.sh